#!/bin/bash

Rscript --vanilla -e 'roxygen2::roxygenize()' > /dev/null

if [ "$1" == "-c" ] || [ "$2" == "-c" ] ; then
    bash cleanup
fi

if [ "$1" == "-d" ] || [ "$2" == "-d" ] ; then
    mv src/Makevars.in src/Makevars.rel
	ln src/Makevars.dbg src/Makevars.in
    R CMD INSTALL --debug --no-multiarch --with-keep.source .
    rm src/Makevars.in
    mv src/Makevars.rel src/Makevars.in
else
    R CMD INSTALL --no-multiarch --with-keep.source .
fi
