#!/bin/bash

R --no-readline --silent --vanilla -e 'library(roxygen2); roxygenize();' > /dev/null

if [ "$1" == "-c" ] || [ "$2" == "-c" ] ; then
    bash cleanup
fi

if [ "$1" == "-d" ] || [ "$2" == "-d" ] ; then
	ln src/Makevars.dbg src/Makevars.in
    R CMD INSTALL --debug --no-multiarch --with-keep.source .
else
    ln src/Makevars.rel src/Makevars.in
    R CMD INSTALL --no-multiarch --with-keep.source .
fi

rm src/Makevars.in
