/*
 * Please do not edit this file -- it ensures that your package will export a
 * 'run_testthat_tests()' C routine that can be used to run the Catch unit tests
 * available in your package.
 */
#include "autoconfig.hpp"

#ifdef PENSE_TESTTHAT_ENABLED

#define TESTTHAT_TEST_RUNNER
#include <testthat.h>

#endif // PENSE_TESTTHAT_ENABLED
