# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
on:
  push:
    branches:
      - 'feature/**'
      - 'main'

name: 'R CMD check (dev version of RcppArmadillo)'

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: devel
          http-user-agent: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, local::., remotes
          needs: check

      - name: Install RcppArmadillo from GitHub
        run: remotes::install_github("rcppcore/rcpparmadillo")
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: false
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
          _R_CHECK_CRAN_INCOMING_: false
